import { IsDateString, IsNotEmpty, IsOptional, isString } from "class-validator";
/**
 * 
 * Class which represents a person over the wire at internal API level.
 * User to create and retrieve a policyholder
 * 
 */
export class PersonDto {

    /** represents the uid in SCV for this Person */
    @IsNotEmpty()
    uid: string;

    @IsNotEmpty()
    firstName: string;

    @IsNotEmpty()
    secondName: string;

    /** ISO date format */
    @IsNotEmpty()
    dob: string;

    /** not used, if you want to set the postcode set the legal address */
    @IsOptional()
    residentialPostCode: string;

    /** not used */
    @IsOptional()
    email: string;

    /** not used */
    @IsOptional()
    tel: string;

    /** date created in SCV, not the LOB appication */
    @IsOptional()
    @IsDateString()
    createdDate: string;

    /** date last updated in SCV, not in the LOB application */
    @IsOptional()
    @IsDateString()
    lastUpdatedDate: string;

    /**
     * the channel this person was captured on
     * not used in LOB application
     */
    @IsOptional()
    sourceChannel: string;

    /**
     * the commercial partner this person was generated by
     * not used in the LOB application
     */
    @IsOptional()
    partnerCode: string;

    /**
     * the brand which first captured this person
     * not used in the LOB application
     */
    @IsOptional()
    captureBrand: string;

 }